# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'K8s service connection'
    command: 'login'

- task: Kubernetes@2
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kuber-brief7-gs'
    namespace: 'brief7-gs'
    command: 'top'
    arguments: 'pod'
  name: 'prout'
- bash: echo $prout

- task: CmdLine@3
  inputs:
    script: |
      cat /home/ely/version/version.vote
      mkdir /home/ely/version
      mkdir /home/ely/git
      pwd
      TESTVAR=$(curl 'https://hub.docker.com/v2/repositories/simplonasa/azure_voting_app/tags' | jq '."results"[0]["name"]')
      echo "$TESTVAR"|sed 's/^.//;s/.$//' >/home/ely/version/version.vote
      cat /home/vsts/version/version.vote