# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 * * * *" # cron syntax defining the schedule - every hour at 0'
  displayName: Hourly main schedule # friendly name given to a specific schedule
  branches:
    include: # which branches the schedule applies to
    - main 
#    exclude: # which branches to exclude from the schedule
#    - [string]
  always: false # whether to always run the pipeline or only if there have been source code changes since the last successful scheduled run. The default is false.

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'K8s connection'
    command: 'login'

- task: CmdLine@1
  inputs:
    script: |
      cat /home/vsts/version/version.vote
      mkdir /home/vsts/version
      mkdir /home/vsts/git
      pwd
      ls -la
      
      # Retrieve the version of the image into file for secret
      TESTVAR=$(curl 'https://hub.docker.com/v2/repositories/simplonasa/azure_voting_app/tags' | jq '."results"[0]["name"]')
      echo "$TESTVAR"|sed 's/^.//;s/.$//' >/home/vsts/version/version.vote
      cat /home/vsts/version/version.vote
      
      # Retrieve the value of the secret
      SECRET_VALUE=$(kubectl get secret my-secret -o jsonpath={.data.version})

      # Compare the version number with the secret value
      if [ "$TESTVAR" != "$SECRET_VALUE" ]; then
        # Update the secret with the new version number
        kubectl patch secret my-secret -p "{\"data\":{\"version\":\"$TESTVAR\"}}"
      fi

- task: Kubernetes@2
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'K8s connection'
    command: 'apply'
    useConfigurationFile: true
    configuration: '/home/vsts/work/1/s/vote-renew2.yml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
  displayName: 'K8s Infra'
  condition: : on_success
