# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'K8s service connection'
    command: 'top'
    arguments: 'pod'


- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'K8s service connection'
    command: 'apply'
    useConfigurationFile: true
    configuration: './part1/Red_Vote.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'


- task: CmdLine@2
  inputs:
    script: 'bash ./part1/delete.sh'